# Server
server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ledgerx
spring.datasource.username=ledgerx_user
spring.datasource.password=ledgerx_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# App name
spring.application.name=auth-service

# JWT
jwt.secret=ledgerx-super-secret-key-must-be-at-least-256-bits-long-for-hmac
jwt.expiry-ms=900000